volumes:
  pg_data:
    name: notes_pg_data

  notes_storage:
    name: notes_service_volume

networks:
  network:
    driver: bridge
    name: notes_network

services:
  web:
    container_name: todo_web
    build:
      context: web
    ports:
      - "3000:3000"
    restart: always

  auth1:
    container_name: todo_auth_1
    build:
      context: grpc-auth
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      network:
        aliases:
          - auth-service-hub
    restart: always

  auth2:
    container_name: todo_auth_2
    build:
      context: grpc-auth
    ports:
      - "8001:8000"
      - "9001:9000"
    networks:
      network:
        aliases:
          - auth-service-hub
    restart: always

  auth3:
    container_name: todo_auth_3
    build:
      context: grpc-auth
    ports:
      - "8002:8000"
      - "9002:9000"
    networks:
      network:
        aliases:
          - auth-service-hub
    restart: always

  user_todo_db:
    image: postgres:18
    container_name: user_todo_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - path: ./.env
    volumes:
      - ./grpc-auth/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:7432:5432"
    networks:
      - network
    restart: always

  notes_db_instance:
    image: postgres:18
    container_name: notes_db_new
    environment:
      - POSTGRES_DB=${DB_NAME_NOTES}
      - POSTGRES_USER=${DB_USER_NOTES}
      - POSTGRES_PASSWORD=${DB_PASSWORD_NOTES}
    volumes:
      - ./note-service/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - notes_storage:/var/lib/postgresql
    ports:
      - "127.0.0.1:8432:5432"
    networks:
      - network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  note_app_1:
    container_name: note_srv_1
    build:
      context: note-service
    ports:
      - "9080:8080"
    environment:
      - DB_HOST=notes_db_instance
      - DB_PORT=5432
      - DB_NAME=${DB_NAME_NOTES}
      - DB_USER=${DB_USER_NOTES}
      - DB_PASS=${DB_PASSWORD_NOTES}
      - AUTH_SERVICE_HOST=auth-service-hub
    networks:
      - network
    depends_on:
      notes_db_instance:
        condition: service_healthy
    restart: always

  note_app_2:
    container_name: note_srv_2
    build:
      context: note-service
    ports:
      - "9081:8080"
    environment:
      - DB_HOST=notes_db_instance
      - DB_PORT=5432
      - DB_NAME=${DB_NAME_NOTES}
      - DB_USER=${DB_USER_NOTES}
      - DB_PASS=${DB_PASSWORD_NOTES}
      - AUTH_SERVICE_HOST=auth-service-hub
    networks:
      - network
    depends_on:
      notes_db_instance:
        condition: service_healthy
    restart: always

  note_app_3:
    container_name: note_srv_3
    build:
      context: note-service
    ports:
      - "9082:8080"
    environment:
      - DB_HOST=notes_db_instance
      - DB_PORT=5432
      - DB_NAME=${DB_NAME_NOTES}
      - DB_USER=${DB_USER_NOTES}
      - DB_PASS=${DB_PASSWORD_NOTES}
      - AUTH_SERVICE_HOST=auth-service-hub
    networks:
      - network
    depends_on:
      notes_db_instance:
        condition: service_healthy
    restart: always