events {
    worker_connections 1024;
}

http {
    upstream note_services {
        server note_srv_1:8080;
        server note_srv_2:8080;
        server note_srv_3:8080;
    }

    server {
        listen 8888;

        location / {
            proxy_pass http://note_services;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
    }
}